# ── Stage 1: Build ────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

# Variables de Vite en tiempo de build (sobreescribibles con --build-arg)
ARG VITE_USE_REMOTE_API=true
ARG VITE_API_BASE_URL=/api/v1
ARG VITE_API_TIMEOUT_MS=10000
ARG VITE_SHOW_REMOTE_DEMO_CREDENTIALS=false
ARG VITE_REMOTE_DEMO_ADMIN_EMAIL=
ARG VITE_REMOTE_DEMO_ADMIN_PASSWORD=
ARG VITE_REMOTE_DEMO_CUSTOMER_EMAIL=
ARG VITE_REMOTE_DEMO_CUSTOMER_PASSWORD=

ENV VITE_USE_REMOTE_API=$VITE_USE_REMOTE_API
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_API_TIMEOUT_MS=$VITE_API_TIMEOUT_MS
ENV VITE_SHOW_REMOTE_DEMO_CREDENTIALS=$VITE_SHOW_REMOTE_DEMO_CREDENTIALS
ENV VITE_REMOTE_DEMO_ADMIN_EMAIL=$VITE_REMOTE_DEMO_ADMIN_EMAIL
ENV VITE_REMOTE_DEMO_ADMIN_PASSWORD=$VITE_REMOTE_DEMO_ADMIN_PASSWORD
ENV VITE_REMOTE_DEMO_CUSTOMER_EMAIL=$VITE_REMOTE_DEMO_CUSTOMER_EMAIL
ENV VITE_REMOTE_DEMO_CUSTOMER_PASSWORD=$VITE_REMOTE_DEMO_CUSTOMER_PASSWORD

COPY . .
RUN npm run build

# ── Stage 2: Serve ─────────────────────────────────────────────────────────────
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
